### ISSUE TITLE
Mod broke after recent update

### ISSUE THREAD

**Issue by Badagronk** [AsteriskAmpersand/Ice-Stable#10]
Hi,

An update just modified the exe and "chunkg10.bin": https://steamdb.info/depot/582011/history/?changeid=M:3388885539667572621
The mod now shows an "ICE consistency error" popup on boot.
Is there a workaround?

Kind regards.

**Comment by bobberson7** [comment]
Was having that same issue, now after the recent google drive robustness release the installer is giving me a "Unable to update CU" error. Unsure if this is an issue with the manager release or the recent MHW patch

**Comment by AsteriskAmpersand** [comment]
Fixed in b7400a03f65f96950a44cf7b2efed4db14b4bdc2
