### ISSUE TITLE
Content Update Error?

### ISSUE THREAD

**Issue by bobberson7** [AsteriskAmpersand/Ice-Stable#11]
![ERROR](https://github.com/AsteriskAmpersand/Ice-Stable/assets/16256420/7e008397-e8ec-42c4-b529-847c5229ac1d)

Error following newest release and steam update for MHW Iceborne. Unsure if the issue is related or separate.

**Comment by OhMyGarm** [comment]
I get same error as well as the game can't open.

**Comment by AsteriskAmpersand** [comment]
CU01 is not necessary for current ICE version. Instructions are clear. Try reinstalling in 24 hours or manually. This is a problem of google drive (which hosts the CUs) running out of capacity. It will not stop ICE from running that's an unrelated problem.

**Comment by stripedypaper** [comment]
what are the instructions to manually install the CUs?
