### ISSUE TITLE
Monster Hunter World is not running in compatibility mode

### ISSUE THREAD

**Issue by JavierArmesto** [AsteriskAmpersand/Ice-Stable#12]
When i start the game a window pops up that says "Corrupted ICE install. Check that MHW is not running in compatibility mode".
Itried to re-install ICE both the stable and experimental versions and this message allways pops up. I didnt disable the compatibility mode because i dont know how. I would appreciate it if you could help me.

**Comment by AsteriskAmpersand** [comment]
That is not an ICE problem, that's a windows problem. Look it up, google is your friend.
