### ISSUE TITLE
Error:01-00-00

### ISSUE THREAD

**Issue by LiothGold** [AsteriskAmpersand/Ice-Stable#13]
This suddenly began happening about 3-ish days after I initially installed this. No clue what's causing this. Did a complete reinstall of both the mod and the game proper and the issue persists. The compatibility settings aren't the problem either, as all boxes are unchecked. Hell I've even moved the game files onto an entirely different drive, and even tried on a different computer, same problem.

**Comment by VaporMoon** [comment]
There was a patch for MHW today and it has caused some mods to break, that is why it is not working.

**Comment by LiothGold** [comment]
> There was a patch for MHW today and it has caused some mods to break, that is why it is not working.

Really? There was no download via Steam, and it was all working fine about ten-ish hours ago. The only thing that happened between then and now was my computer being restarted.

**Comment by VaporMoon** [comment]
Patch was released 10hours ago.

**Comment by LiothGold** [comment]
> Patch was released 10hours ago.

Ah... so when will the fixed version be out? Next few days I hope.
