### ISSUE TITLE
Issues with Windows compatibility options

### ISSUE THREAD

**Issue by harlowthefish** [AsteriskAmpersand/Ice-Stable#2]
I'm having an issue with MHW (unrelated, I think, to ICE) where the game doesn't respect being set to fullscreen and runs in a window anyway. If I use Windows' compatibility options to disable fullscreen optimizations, MHW itself will run properly in fullscreen, but ICE will error out on launch, telling me that I have a corrupted ICE install (error 01-00-00, according to the popup) and to disable any compatibility settings.

I can use borderless, but that's a hefty performance penalty on my rig, and neither the in-game fullscreen option or using Alt+Enter to set the game to fullscreen will work without that compatibility option. Any thoughts?

**Comment by AsteriskAmpersand** [comment]
Have you tried to disable it at settings level instead of at compatibility mode level?
https://www.minitool.com/news/disable-fullscreen-optimizations.html
