### ISSUE TITLE
[Enhancement] Change pick-up priorities between combat and non-combat situations

### ISSUE THREAD

**Issue by jvulcan** [AsteriskAmpersand/Ice-Stable#3]
Currently, your character always prioritizes picking up slinger ammo over anything else.
I suggest to change that to:
- If in combat, prioritize picking up slinger ammo.
- If out of combat, leave slinger ammo to the least priority.
Thank you

Currently slinger ammo is higher priority regardless of combat or non-combat stance. Making it difficult to pick up dropped items from Bandit mantle and sometimes dropped items from guiding lands as well.

**Comment by AsteriskAmpersand** [comment]
The game default behavior already does this. In combat it prioritizes slinger ammo, out of combat it prioritizes drops. However the period for "out-of-combat" might be longer than you expect.
