### ISSUE TITLE
Fatalis Armor

### ISSUE THREAD

**Issue by Randmuserr** [AsteriskAmpersand/Ice-Stable#4]
The changes made to the fatalis armor while understandable from a variety perspective, making one of the set bonuses fundamentally unobtainable is bs frankly and whilst making said changes make sense for your development plans making the changes before the content is released makes the armor undesirable and pointless.

**Comment by AsteriskAmpersand** [comment]
Not a bug or issue. The set bonus removed is unworkable and broken. Its not based on future plans its based on the current state of things.
