### ISSUE TITLE
[suggestion] implement MH4U style concurrent CB AED explosions.

### ISSUE THREAD

**Issue by Shadowex3** [AsteriskAmpersand/Ice-Stable#5]
With the _extreme_ mobility of monsters in iceborne the leisurely sequential explosions are unreasonably hampered. The almost-MH4U style of having all the AED explosions burst in a roughly spherical pattern centered on the axe head is much more suitable for an attack that already has a pretty long windup and low mobility. Monsters can still jump through the explosions but it's much less likely that they'll escape the bulk of the damage.

The one downside is it apparently causes a glitch in the lighting system, flashbanging the player with some elements.

**Comment by AsteriskAmpersand** [comment]
May you perhaps be referring to SAED? AED explosions attach to the monster on the point of contact and their timing of detonation is irrelevant to the final result as they track the monster movement. SAED are the ground explosions. 

If you mean SAED: The sequential aspect of the explosions is part of the move itself. It's a consideration you need to take into account before firing and it should inform your positioning. Simultaneous explosions are imbalanced, it reverts CB back to blind firing of SAEDs. It was tested along other variations and quickly found to be over-centralizing and devalues positioning. Said change is contrary to the aims of ICE and we have no plans on re-including that change.

**Comment by Shadowex3** [comment]
The sequential aspect of the explosions are a part of the move itself. And it's a part of the move itself which was designed without accounting for iceborne's spastic crack monkey on meth monster movement, which is a fundamental error in design just like MHR's explosion height sailing right under even short monster hitboxes is a fundamental error in design.

If anything the current pattern is what rewards spamming and disincentivizes skillful play as you're more far more likely to miss some or most of your explosions through no fault of your own, and similarly more likely to get at least some hits by simply cranking them out as much as possible when the monster is (or might be) in the general area of your long slow spread out set of explosions. This pushes all but the most perfect of players towards simply cranking SAEDs out any time it _looks_ like you _might_ get _some_ hits. 

On the other hand a tight cluster of simultaneous explosions is an all or nothing proposition. You get one shot, at one moment, in one tight target zone. If you skillfully time that windup and attack animation you're rewarded, if you blindfire you lose everything.

The only way I could see the current pattern not directly rewarding the thing you say you want to reduce is if you kept the extended pattern but made them all go off at once, turning it from a DoT crowd control ability back into a stringently timed high risk high reward move.
