### ISSUE TITLE
SnS (potential) bug. 

### ISSUE THREAD

**Issue by Arieos** [AsteriskAmpersand/Ice-Stable#6]
Can no longer use advancing slash against walls to go into helm breaker. Not sure if this is intended or not.

**Comment by AsteriskAmpersand** [comment]
Documented in the changelog:

```
The Helm Breaker attack (aka Helm Splitter) has been reworked to offer a sword-based alternative to Falling Bash. This change provides hunters with additional combo choices and allows them to choose between the benefits of sword vs shield attacks, just as they can for ground-based moves.

Helm Breaker
Can now be performed in the air after a successful Charged Slash using △ + O on PS or Y + B on XB (was only available after scaling a wall)."

```

While it would have been ideal to keep both versions, it's ultimately more work on the modding side to keep both. Plus the new way to initiate a Helm Breaker is generally more accessible (can perform in any area vs only on specific walls) and stronger overall (You get the benefits of Charged Slash + Scaling Slash in addition to the Helm Breaker hits), so it wasn't considered a huge loss to lose the ability to initiate it from a wall. Pretty sure the new way is also faster in general (timing from start to finish)
