### ISSUE TITLE
Linux (Proton) Compatibility

### ISSUE THREAD

**Issue by jefferyrlc** [AsteriskAmpersand/Ice-Stable#7]
Vanilla MHW and normal mods work. ICE just tells me my install is corrupted and closes.

FWIW:
OS: Arch Linux x86_64 
Host: MS-7C37 1.0 
Kernel: 6.4.3-273-tkg-pds 
Uptime: 3 hours, 26 mins 
Packages: 1513 (pacman), 10 (flatpak) 
Shell: fish 3.6.1 
Resolution: 1920x1080 
DE: Plasma 
WM: kwin 
Theme: Sweet [Plasma], Sweet-Dark [GTK2/3 
Icons: [Plasma], candy-icons [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
GPU: AMD ATI Radeon RX 6800/6800 XT
Memory: 17891MiB / 32015MiB
![Screenshot_20230713_014846](https://github.com/AsteriskAmpersand/Ice-Stable/assets/18264856/bc784f80-c1ff-49b6-aa84-b05d7b098268)
[steam-582010.log](https://github.com/AsteriskAmpersand/Ice-Stable/files/12035842/steam-582010.log)

**Comment by v1ld** [comment]
Follow the instructions in #unsupported-patches on the mod's Discord. Disable the High Res Textures DLC. This lets me run it on the Deck, but haven't verified on my Arch install - see no reason why that wouldn't work though.

**Comment by Calslock** [comment]
Doesn't work anymore, installing patch from Discord results in the same error as on the image from first post. Also launcher doesn't work, it crashes during installation because of "!CRCBypass.dll" not found, and the only way to install is manually.

**Comment by AsteriskAmpersand** [comment]
#unsupported-patches on the Discord has the most up to date Steam Deck/Linux compatibility patches. As the name says its unsupported. The patch is provided as is and is not officially supported by us.

**Comment by jabocg** [comment]
Is there a plan to eventually support Linux/Proton officially?

**Comment by AsteriskAmpersand** [comment]
No. Not that it'd make any difference given this is a free game modification and we have no binding obligation to the components we officially support anyway.
